### ISSUE TITLE
Mis content item 17

### ISSUE THREAD

**Issue by xlanex6** [xlanex6/DreamstonesV2#15]
on process page - forgot planning approuval content
<img width="918" alt="capture d ecran 2016-12-17 a 09 04 46" src="https://cloud.githubusercontent.com/assets/13418668/21285414/f7038b54-c437-11e6-8c8c-e61453d4c36a.png">

**Comment by xlanex6** [comment]
Planning approval

**Comment by xlanex6** [comment]
il y a un blanc ......
On mets quoi.

**Comment by SamCastello** [comment]
Once all the divisions of the planning authorities have given their positive feedback on the project, the approval is given. You will therefore receive the exiting news by post.
