### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by SamCastello** [xlanex6/DreamstonesV2#25]
![screen shot 2016-12-17 at 00 27 30](https://cloud.githubusercontent.com/assets/23459511/21282936/a21e9916-c3f2-11e6-8618-2c2c68c76c83.png)

**Comment by xlanex6** [comment]
The background pic is there........on production
<img width="1239" alt="capture d ecran 2016-12-17 a 08 53 05" src="https://cloud.githubusercontent.com/assets/13418668/21285356/56e06d78-c436-11e6-8aef-79ee1bf393ab.png">

**Comment by xlanex6** [comment]
if you you swap it. send me original.

**Comment by xlanex6** [comment]
C'est l'objectif sur cette page. 


<img width="400" alt="capture d ecran 2016-12-17 a 09 22 48" src="https://cloud.githubusercontent.com/assets/13418668/21285499/8c0c7704-c43a-11e6-9fce-1fb75355676d.png">
