### ISSUE TITLE
obtain DNS access

### ISSUE THREAD

**Issue by SamCastello** [xlanex6/DreamstonesV2#41]

**Comment by SamCastello** [comment]
message de Francois, le webmaster:

Pour les accès aux domaines, il faudrait m’envoyer (et créer le cas échéant), un nic handle chez OVH. Je pourrai alors faire un changement de délégation complet et vous aurez la main sur l’ensemble des services.


@xlanex6 tu vois comment faire?

**Comment by xlanex6** [comment]
jamais fait mais je me mets dessus. ca dois pas etre compliqué

**Comment by SamCastello** [comment]
ok , dis moi si tu as besoin de quoique ce soit

**Comment by xlanex6** [comment]
Ok apres lecture
On doir créer un compte OVH, pour dreamstones, on catch le nic handle, on lui donne et il nous transfert le bordel
simple et efficasse
en theorie...

**Comment by SamCastello** [comment]
ok chaud
dis nous s'il faut payer

**Comment by SamCastello** [comment]
en attente de francois...

**Comment by xlanex6** [comment]
Aucune infos, aucune notification dans OVH
Un truc déconne, il faut appeler le webmaster
